# Generated by Django 5.1 on 2024-08-31 19:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('ingredients', models.ManyToManyField(to='inventory.foodorderitem')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItemRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_brunch', models.BooleanField(default=False)),
                ('is_social_hour', models.BooleanField(default=False)),
                ('recipes', models.ManyToManyField(to='recipe.kitchenrecipe')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
