# Generated by Django 5.1.1 on 2024-11-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_barrecipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemrecipe',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
