PHONE_REGEX = '^(\+?\d{0,2})?[\D]?\(?(\d{3})\)?[\D]?(\d{3})[\D]?(\d{4})$'  # noqa: W605 E501

FOOD_ORDER_ITEM_UNIT_CHOICES = [
    ('cs', 'cs'),
    ('btl', 'btl'),
    ('box', 'box'),
    ('can', 'can'),
    ('bucket', 'bucket'),
    ('ea', 'ea'),
    ('flats', 'flats'),
    ('sticks', 'sticks'),
    ('#', '#'),
    ('lbs', 'lbs'),
    ('gal', 'gal'),
    ('oz', 'oz'),
    ('dz', 'dz'),
    ('as needed', 'as needed')
]

REGION_AREA_CHOICES = [
    ('Argentina', 'Argentina'),
    ('Australia', 'Australia'),
    ('Austria', 'Austria'),
    ('Barbados', 'Barbados'),
    ('Barbados', 'Barbados'),
    ('Belgium', 'Belgium'),
    ('Brazil', 'Brazil'),
    ('Bulgaria', 'Bulgaria'),
    ('Canada', 'Canada'),
    ('Caribbean', 'Caribbean'),
    ('Chile', 'Chile'),
    ('China', 'China'),
    ('Cuba', 'Cuba'),
    ('Czech Republic', 'Czech Republic'),
    ('Dominican Republic', 'Dominican Republic'),
    ('England', 'England'),
    ('France', 'France'),
    ('Georgia', 'Georgia'),
    ('Germany', 'Germany'),
    ('Greece', 'Greece'),
    ('Guadeloupe', 'Guadeloupe'),
    ('Guatemala', 'Guatemala'),
    ('Guyana', 'Guyana'),
    ('Haiti', 'Haiti'),
    ('Hungary', 'Hungary'),
    ('India', 'India'),
    ('Ireland', 'Ireland'),
    ('Israel', 'Israel'),
    ('Italy', 'Italy'),
    ('Jamaica', 'Jamaica'),
    ('Japan', 'Japan'),
    ('Mauritius', 'Mauritius'),
    ('Martinique', 'Martinique'),
    ('Mexico', 'Mexico'),
    ('Netherlands', 'Netherlands'),
    ('New Zealand', 'New Zealand'),
    ('Nicaragua', 'Nicaragua'),
    ('Puerto Rico', 'Puerto Rico'),
    ('Panama', 'Panama'),
    ('Philippines', 'Philippines'),
    ('Portugal', 'Portugal'),
    ('Romania', 'Romania'),
    ('Russia', 'Russia'),
    ('Saint Lucia', 'Saint Lucia'),
    ('Scotland', 'Scotland'),
    ('Slovenia', 'Slovenia'),
    ('South Africa', 'South Africa'),
    ('Spain', 'Spain'),
    ('Switzerland', 'Switzerland'),
    ('Taiwan', 'Taiwan'),
    ('Thailand', 'Thailand'),
    ('Trinidad/Tobago', 'Trinidad/Tobago'),
    ('Turkey', 'Turkey'),
    ('United States', 'United States'),
    ('Venezuela', 'Venezuela'),
    ('Wales', 'Wales')
]

COCKTAIL_CATEGORY_CHOICES = [
    ('Beer-based', 'Beer-based'),
    ('Classic/Vintage', 'Classic/Vintage'),
    ('Contemporary Classic', 'Contemporary Classic'),
    ('Hot', 'Hot'),
    ('Levitate Menu', 'Levitate Menu'),
    ('Long Drinks/Highballs', 'Long Drinks/Highballs'),
    ('Martini', 'Martini'),
    ('Modern', 'Modern'),
    ('Molecular', 'Molecular'),
    ('Non-Alcoholic', 'Non-Alcoholic'),
    ('Punch', 'Punch'),
    ('Shots', 'Shots'),
    ('Sours', 'Sours'),
    ('Tiki/Tropical', 'Tiki/Tropical'),
    ('Wine-based', 'Wine-based'),
]

BASE_SPIRIT_CHOICES = [
    ('Vodka', 'Vodka'),
    ('Gin', 'Gin'),
    ('Rum', 'Rum'),
    ('Tequila', 'Tequila'),
    ('Mezcal', 'Mezcal'),
    ('Brandy', 'Brandy'),
    ('Liqueur', 'Liqueur'),
    ('Bourbon', 'Bourbon'),
    ('Rye', 'Rye'),
    ('Scotch', 'Scotch'),
    ('Cachaca', 'Cachaca'),
    ('Genever', 'Genever'),
    ('Pisco', 'Pisco'),
    ('Other', 'Other'),
    ('Split', 'Split'),
]

BEER_STYLE_AREA_CHOICES = [
        ('Belgium/France', 'Belgium/France'),
        ('England', 'England'),
        ('Scotland', 'Scotland'),
        ('Ireland', 'Ireland'),
        ('Germany/Czech Republic/Austria', 'Germany/Czech Republic/Austria'),
        ('United States', 'United States'),
        ('International', 'International'),
        ('Australia', 'Australia'),
        ('Poland', 'Poland'),
        ('Scandinavia', 'Scandinavia'),
        ('Other', 'Other')
]
