# Generated by Django 5.1 on 2024-08-27 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('par', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('quantity_on_hand', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('product_identifier', models.CharField(blank=True, max_length=64)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('area', models.CharField(choices=[('Kitchen', 'Kitchen'), ('Bar', 'Bar'), ('Other', 'Other')], default='Kitchen', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodOrderItem',
            fields=[
                ('baseinventoryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseinventoryitem')),
                ('unit', models.CharField(choices=[('cs', 'cs'), ('box', 'box'), ('can', 'can'), ('bucket', 'bucket'), ('ea', 'ea'), ('flats', 'flats'), ('sticks', 'sticks'), ('#', '#'), ('lbs', 'lbs'), ('gal', 'gal'), ('oz', 'oz'), ('dz', 'dz'), ('as needed', 'as needed')], default='cs', max_length=9)),
                ('latest_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('inventory.baseinventoryitem',),
        ),
        migrations.AddField(
            model_name='baseinventoryitem',
            name='category',
            field=models.ManyToManyField(to='inventory.category'),
        ),
    ]
