# Generated by Django 5.1.1 on 2024-11-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_beerorderitem_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerorderitem',
            name='menu_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='spiritorderitem',
            name='menu_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='wineorderitem',
            name='menu_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
