# Generated by Django 5.1.1 on 2024-11-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_beerorderitem_menu_price_spiritorderitem_menu_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerorderitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spiritorderitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spiritorderitem',
            name='is_well',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wineorderitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wineorderitem',
            name='is_glass_pour',
            field=models.BooleanField(default=True),
        ),
    ]
