# Generated by Django 5.1.1 on 2024-11-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_beerorderitem_is_active_spiritorderitem_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerorderitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spiritorderitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wineorderitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
