# Generated by Django 5.1.1 on 2024-12-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
    ]
